// Code generated by go2struct. DO NOT EDIT.
package config

type Settings struct {
	Application struct {
		Mode string `mapstructure:"mode"`
		Port int    `mapstructure:"port"`
	} `mapstructure:"application"`
}
